### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by MaximillianJacob** [MaximillianJacob/github-action-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
.yellow-bold-link {
    color: #3c4ace;
    font-weight: bold;
    text-decoration: underline;
}

```
